### ISSUE TITLE
Help With an Error and a Global Map

### ISSUE THREAD

**Issue by MaxFrissell** [MaxFrissell/SoilRespirationPartitioning#24]
Please take a look at the `GlobalPredictionRF.Rmd` file in the __GlobalPrediction__ branch and try and fix the error that I don't understand. All data you need should be in dropbox.

Also, please make a map of the global RC predictions. They are stored with their coordinates in the `globalWithP` dataframe.

**Comment by bpbond** [comment]
Taking a look. All the needed were not actually in Dropbox, so have some things to download first. But **you have good documentation on where to go for the data** -- excellent, thank you!

**Comment by bpbond** [comment]
Oh wait, you prepended your name in front of the datasets before uploading? Ah. Got it.

**Comment by bpbond** [comment]
Woo hoo!

![predict](https://user-images.githubusercontent.com/1956468/90504186-b29b1d80-e11e-11ea-97d7-7a64c34c1a1d.png)

**Comment by bpbond** [comment]
Better colors:

![predict](https://user-images.githubusercontent.com/1956468/90505160-2558c880-e120-11ea-8768-a5fcf063448b.png)

Anyway, committing and opening a PR.

**Comment by MaxFrissell** [comment]
Wooooooooooooaaaaaaaaah

**Comment by MaxFrissell** [comment]
Thats awesome
