### ISSUE TITLE
Weeks 4-5

### ISSUE THREAD

**Issue by bpbond** [MaxFrissell/SoilRespirationPartitioning#8]
- [x] Work with Steph's WorldClim2 code and incorporate
- [x] Build out table in #7 listing datasets we're using. Initially this should include WorldClim2, N deposition, Spawn biomass, and Soudzilovskaia mycorrhizae
- [ ] Ben to email Seth and Nadja re datasets - #12 
- [x] Pick what looks like next-easiest dataset (e.g. same format?) and build code to extract those data
- [ ] Keep in touch with me and @jinshijian re progress and questions
- [x] We'll plan on a journal club meeting next week, re machine learning?

**Comment by bpbond** [comment]
Hey @MaxFrissell can you post some of your WorldClim2 graphs and results? Thanks.

**Comment by MaxFrissell** [comment]
![image](https://user-images.githubusercontent.com/63824873/87346227-53def480-c51f-11ea-9f89-97aa90282c66.png)
![image](https://user-images.githubusercontent.com/63824873/87346243-59d4d580-c51f-11ea-86f5-614d5ff9bdc5.png)

**Comment by bpbond** [comment]
There will be a few more columns we're going to want to extract from SRDB - you and @jinshijian and I can talk about this.

**Comment by MaxFrissell** [comment]
![image](https://user-images.githubusercontent.com/63824873/87346403-a0c2cb00-c51f-11ea-8587-68c3a46aeb52.png)
![image](https://user-images.githubusercontent.com/63824873/87346415-a5877f00-c51f-11ea-8a1f-49e3401780f0.png)

**Comment by MaxFrissell** [comment]
Just finished extracting from the mycorrhizae dataset. You can check it out in the extracting from datasets RMarkdown file. I also made some graphs.

**Comment by bpbond** [comment]
@MaxFrissell Awesome! Can you paste a figure or two here?

**Comment by MaxFrissell** [comment]
![image](https://user-images.githubusercontent.com/63824873/87465009-08d9e580-c5e2-11ea-959e-76780217f5bb.png)

This is just the one from before, but only with the entries with RC_annual

![image](https://user-images.githubusercontent.com/63824873/87465088-20b16980-c5e2-11ea-9c06-f71a33ebc8c6.png)
![image](https://user-images.githubusercontent.com/63824873/87465101-2444f080-c5e2-11ea-9f5f-cacba4ffc5e8.png)

![image](https://user-images.githubusercontent.com/63824873/87465178-36269380-c5e2-11ea-8632-b7cb5edd45ab.png)
![image](https://user-images.githubusercontent.com/63824873/87465204-3e7ece80-c5e2-11ea-9457-df60184c34a8.png)

There are more of each type I sent, but these are the ones that look the most interesting.

**Comment by bpbond** [comment]
Nice! 👏

**Comment by MaxFrissell** [comment]
Now some biomass graphs!

![image](https://user-images.githubusercontent.com/63824873/87586619-c7633c00-c6ae-11ea-9914-17ee37f75393.png)
![image](https://user-images.githubusercontent.com/63824873/87586626-caf6c300-c6ae-11ea-9193-ac2f5ffb5501.png)
They don't look super great since I just don't have that many points and also the biomass rarely varies so much to make it really bright on these scales.

**Comment by bpbond** [comment]
Exciting! Yes, I think it's time to learn about using different color scales. You might touch base with @jinshijian or @stephpenn1 on this topic.

**Comment by MaxFrissell** [comment]
Just finished extracting my N deposition data

![image](https://user-images.githubusercontent.com/63824873/88194460-df860e80-cc0c-11ea-854a-e4dfa8f2c5f7.png)
![image](https://user-images.githubusercontent.com/63824873/88194475-e3199580-cc0c-11ea-9d6e-00021623cfec.png)
![image](https://user-images.githubusercontent.com/63824873/88194497-e9a80d00-cc0c-11ea-8ad7-2876590b1cf1.png)

**Comment by stephpenn1** [comment]
There graphs are awesome! Nice work @MaxFrissell. Here are some functions for adding different color scales to your plots: https://ggplot2.tidyverse.org/reference/scale_brewer.html

**Comment by MaxFrissell** [comment]
Oh nice, I'll check those out.
